//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularRouting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long Login_id { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public long User_id { get; set; }
        public long Expr1 { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
    }
}
